### Transcribe
POST http://localhost:8000/audio
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="file"; filename="task.wav"
Content-Type: audio/wav

< ./task.wav
--BOUNDARY--

### Text
POST http://localhost:8000/
Content-Type: application/json

{
  "prompt": "Add ice cream to my Grocery list"
}